/* @flow */

// article
export const GET_ARTICLE_PENDING = 'GET_ARTICLE_PENDING'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_ERROR = 'GET_ARTICLE_ERROR'

// session
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

// sites
export const LIST_SITES_PENDING = 'LIST_SITES'
export const LIST_SITES_SUCCESS = 'LIST_SITES_SUCCESS'
export const LIST_SITES_ERROR = 'LIST_SITES_ERROR'

// site
export const GET_SITE_PENDING = 'GET_SITE'
export const GET_SITE_SUCCESS = 'GET_SITE_SUCCESS'
export const GET_SITE_ERROR = 'GET_SITE_ERROR'

// articles
export const LIST_ARTICLES_PENDING = 'LIST_ARTICLES'
export const LIST_ARTICLES_SUCCESS = 'LIST_ARTICLES_SUCCESS'
export const LIST_ARTICLES_ERROR = 'LIST_ARTICLES_ERROR'
